<a href="https://colab.research.google.com/github/lamtruong2002/BaitapAItuan8/blob/main/BT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split #chia du lieu train va test
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler #chuan hoa du lieu cho dữ liệu đều nhau


import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sas



In [49]:
iris=datasets.load_iris()
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)

model=Perceptron(max_iter=40,eta0=0.1,random_state=0) #max_iter là số lần học, tốc độ học nhỏ hơn 1, càng lớn sai số nhiều
model.fit(X_train_std,y_train)
y_pred=model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình:',accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[0 0 0 0 2 2 0 1 1 0 2 2 1 0 2 0 1 0 0 0 1 2 0 2 1 0 2 1 2 1 2 2 0 2 2 1 2
 2 2 2 0 1 1 1 1]
[0 0 0 0 2 2 0 1 1 0 2 2 1 0 2 0 1 0 0 0 1 2 0 2 2 0 2 1 2 0 1 2 0 2 2 1 1
 2 2 1 0 1 2 1 1]
Độ chính xác của mô hình: 0.8666666666666667
