<a href="https://colab.research.google.com/github/lamtruong2002/BaitapAItuan8/blob/main/lung_cancer_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sas
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
data = pd.read_csv('lung_cancer_examples.csv')
print(data.head())
print(data.shape)
data.head()
data.drop(data.columns[[0,1]], axis=1, inplace=True)
X = data[['Age', 'Smokes', 'AreaQ', 'Alkhol']].to_numpy()
y = data['Result'].to_numpy()
print(X[:5])
print(y[:5])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
print(X_train_std[:5])
model = Perceptron(max_iter=40, eta0=0.1, random_state=0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print("Do chinh xac cua mo hinh: ", accuracy_score(y_test,y_pred))

     Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1
(59, 7)
[[35  3  5  4]
 [27 20  2  5]
 [30  0  5  2]
 [28  0  8  1]
 [68  4  5  6]]
[1 1 0 0 1]
[[-1.03595796 -0.28232346  0.36327627 -1.02236092]
 [ 2.04875165  0.66547673 -0.06357335  0.35052374]
 [ 0.5971236   0.66547673  0.36327627 -0.10710448]
 [ 1.80681364 -0.68852354  0.79012588  1.26578018]
 [ 0.89954611 -0.01152341  2.07067473 -1.47998914]]
[0 0 0 1 1 1 1 1 0 1 0 0]
[0 0 0 1 1 1 1 1 0 1 0 0]
Do chinh xac cua mo hinh:  1.0
